const endPoints = {
  login: "/auth/login",
  register: "/auth/register",
  applicants: "/applicants/register",
  createDepartmentHead: "/auth/create-department-head",
  createTeacher: "/auth/create-teacher",
  departmentHeads: "/department-heads",
  teachers: "/teachers",
  applicantDetail: "/applicants/:id",
  departments: "/departments",
  impairments: "/impairments",
  semesters: "/semesters",
  schoolBackgrounds: "/school-backgrounds",
  programModality: "/program-modality",
  classYears: "/class-years",
  semester: "/semesters",
  BatchClassYearSemesters: "/bcsy",
  batches: "/batches",
  courses: "/courses/single",
  regions: "/region",
  zonesByRegion: "/zone/region",
  woredasByZone: "/woreda/zone",
};

export default endPoints;
